"""Tests for scripts/generate_live_report.py — the self-updating HTML
dashboard built from the live-trading state ledgers.

The report is regenerated by CI after every real run and published via
GitHub Pages; these tests pin the data logic (returns, order aggregation,
graceful empty-state) and that the HTML actually carries the numbers.
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.generate_live_report import build_report_html, strategy_summary
from utils.state_store import StateStore


@pytest.fixture
def kelly_store(tmp_path):
    store = StateStore(db_path=str(tmp_path / "kelly.db"))
    store.record_account_snapshot("2026-07-28", equity=25000.0, cash=25000.0, positions={})
    store.record_account_snapshot("2026-07-29", equity=25539.77, cash=9056.77,
                                  positions={"TQQQ": 16483.0})
    store.record_order("2026-07-28", "TQQQ", "buy", 265, "order-1", "accepted")
    store.record_order("2026-07-29", "TQQQ", "buy", 10, "order-2", "accepted")
    return store


@pytest.fixture
def empty_store(tmp_path):
    return StateStore(db_path=str(tmp_path / "empty.db"))


def test_total_return_anchored_to_inception_capital(tmp_path):
    """Both paper accounts started at exactly $25,000. The first ledger
    snapshot can NOT be trusted as the inception base: observed live, two
    same-session runs upserted the day's snapshot, overwriting the true
    $25,000 base with the post-gain equity -- which flipped a +1.9%
    track record into a reported -0.29%. Total return must be measured
    against the known inception capital, not the earliest surviving row.
    """
    store = StateStore(db_path=str(tmp_path / "k.db"))
    store.record_account_snapshot("2026-07-28", equity=25539.77, cash=9056.77,
                                  positions={"TQQQ": 16483.0})
    s = strategy_summary("Kelly", store)
    assert s["total_return_pct"] == pytest.approx(100 * (25539.77 / 25000.0 - 1))


def test_strategy_summary_returns_since_inception(kelly_store):
    s = strategy_summary("Kelly", kelly_store)
    assert s["equity"] == pytest.approx(25539.77)
    assert s["total_return_pct"] == pytest.approx(100 * (25539.77 / 25000.0 - 1))
    assert s["n_sessions"] == 2
    assert s["n_orders"] == 2


def test_strategy_summary_day_return_uses_last_two_snapshots(kelly_store):
    s = strategy_summary("Kelly", kelly_store)
    assert s["day_return_pct"] == pytest.approx(100 * (25539.77 / 25000.0 - 1))


def test_strategy_summary_empty_ledger_is_graceful(empty_store):
    # First deploy happens before the first real run -- the report must
    # render a sane empty state, not crash the CI step.
    s = strategy_summary("Linear", empty_store)
    assert s["equity"] is None
    assert s["n_sessions"] == 0
    assert s["n_orders"] == 0


def test_html_contains_key_numbers_and_orders(kelly_store, empty_store):
    html = build_report_html({"Kelly": kelly_store, "Linear": empty_store})
    assert "25,539.77" in html          # current equity
    assert "TQQQ" in html               # order ticker
    assert "265" in html                # order qty
    assert "Kelly" in html and "Linear" in html
    assert "Awaiting first run" in html  # empty-state for Linear


def test_html_is_self_contained(kelly_store):
    # Served from GitHub Pages -- no external scripts/styles/fonts, so it
    # renders identically offline and never breaks on a CDN.
    html = build_report_html({"Kelly": kelly_store})
    assert "<script src=" not in html
    assert "https://cdn" not in html
    assert "@import" not in html
